AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Parameters:
    CodeKey:
        Type: String

Resources:
  SanjanaSSMLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri:
           Bucket: 'sanjana-ssmbucket'
           Key: !Ref CodeKey
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::543816070942:role/SSM_lambda_role_aakankshi'
      Events:
        SNS1:
          Type: SNS
          Properties:
            Topic:
              Ref: SNSTopic1
  SNSTopic1:
    Type: 'AWS::SNS::Topic'
